### PR TITLE
Added socket reuse flag for listen

### PR DESCRIPTION
**Pull request by Imtnt**
A simple change that adds the option to enable socket reuse when calling listen. This is necessary to get clustering to work properly.

### CODE REVIEW

**Comment by zorro-fr24** [comment]
nice.
This boosted performance running on 8 cores by about 60-70%.

without reuse:
```ab -k -c 8 -n 1000000 "http://localhost:1080/"
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Completed 1000000 requests
Finished 1000000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            1080

Document Path:          /
Document Length:        12 bytes

Concurrency Level:      8
Time taken for tests:   8.335 seconds
Complete requests:      1000000
Failed requests:        0
Keep-Alive requests:    1000000
Total transferred:      75000000 bytes
HTML transferred:       12000000 bytes
Requests per second:    119980.77 [#/sec] (mean)
Time per request:       0.067 [ms] (mean)
Time per request:       0.008 [ms] (mean, across all concurrent requests)
Transfer rate:          8787.65 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0    0   0.1      0      18
Waiting:        0    0   0.1      0      18
Total:          0    0   0.1      0      18

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      0
  75%      0
  80%      0
  90%      0
  95%      0
  98%      0
  99%      0
 100%     18 (longest request)
```
with resuse:

```ab -k -c 8 -n 1000000 "http://localhost:1080/"
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100000 requests
Completed 200000 requests
Completed 300000 requests
Completed 400000 requests
Completed 500000 requests
Completed 600000 requests
Completed 700000 requests
Completed 800000 requests
Completed 900000 requests
Completed 1000000 requests
Finished 1000000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            1080

Document Path:          /
Document Length:        12 bytes

Concurrency Level:      8
Time taken for tests:   5.431 seconds
Complete requests:      1000000
Failed requests:        0
Keep-Alive requests:    1000000
Total transferred:      75000000 bytes
HTML transferred:       12000000 bytes
Requests per second:    184133.51 [#/sec] (mean)
Time per request:       0.043 [ms] (mean)
Time per request:       0.005 [ms] (mean, across all concurrent requests)
Transfer rate:          13486.34 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0    0   0.0      0      19
Waiting:        0    0   0.0      0      19
Total:          0    0   0.0      0      19

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      0
  75%      0
  80%      0
  90%      0
  95%      0
  98%      0
  99%      0
 100%     19 (longest request)
```

**Comment by Dmitry-N-Medvedev** [comment]
hi,

how to use it from nodejs?

**Comment by alexhultman** [comment]
HTTP is not even stable, not going to add new "perf options" prematurely

**Comment by Dmitry-N-Medvedev** [comment]
how does socket reuse flag relate to HTTP in the first place?

**Pull request closed without merging**
