### PR TITLE
Client should invoke onclose after onerror

### PR DESCRIPTION
**Pull request by jessetane**
https://html.spec.whatwg.org/multipage/web-sockets.html#closeWebSocket

### CODE REVIEW

**Comment by alexhultman** [comment]
You're referring to HTML. This project is not related to HTML, it relates to `ws`.

**Comment by jessetane** [comment]
https://github.com/websockets/ws/blob/master/lib/websocket.js#L584

**Comment by alexhultman** [comment]
Hmm, that makes no sense. The flow for this lib is:

Connection <-> Disconnection = balance, one is called just as many times the other

After connect call you either land in error or connection, you can't land in disconnection before first being in connection (that would introduce an imbalance between connection and disconnection events).

Also, how can you land in onclose if you first haven't landed in onopen? How can you close something not opened yet?

This lib has its own behavior in that case.

**Comment by jessetane** [comment]
It makes writing code that handles "persistent" connections easier. You can have one handler that deals with retrying the connection regardless of the cause - which could be at connect time, afterward due to network issue, or if the server closed the connection for example.

**Pull request closed without merging**
